apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
#    image: gcr.io/kaniko-project/executor:latest
    image: viniciusramosdefaria/kaniko-test:latest
    args:
    - "--dockerfile=/dockerfile/dockerfile"
    - "--destination=678613036317.dkr.ecr.sa-east-1.amazonaws.com/test:1.1"
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
    - name: dockerfile
      mountPath: /dockerfile
  restartPolicy: Never
  volumes:
  - name: docker-config
    configMap:
      name: docker-config
  - name: dockerfile
    configMap:
      name: dockerfile
